;;; Compiled snippets and support files for `message-mode'
;;; Snippet definitions:
;;;
(yas-define-snippets 'message-mode
                     '(("24x7" "To: 24x7-support-monitor@squiz.net\nSubject: 24x7 Activity Report - `(format-time-string \"%d/%m/%Y\")`\n----\nHi all,\n\n*Outages*:\n\nClient: $0\nTicket:\nNotes:\n\n*Reporting Anomalies (verified as not an outage)*: \n\nClient:\nTicket:\nNotes:\n\nCheers,\nMike\n" "24x7-report" nil nil nil nil nil nil)
                       ("handover" "To: support-team-global@squiz.net\nSubject: AU Support Handover - `(format-time-string \"%d/%m/%Y\")` (${1:All clear|Attention|Emergency})\n----\nG'day UK,\n\n*Notices*\n\n$0\n----\n*instructions*\n\n<client acronym as found in the Squiz intranet> - a brief note regarding the incident. Including details of initial investigation data (e.g. website was completely down | website was up but running slowly | Edge was serving cached content with Matrix down).\n<direct link to the Zendesk ticket>\n\nSubject Line Definitions:\nAll Clear - when there's nothing at all to follow up on or hand over.\nAttention - there is something that needs follow-up, alerting AU of requested scheduled work or you are passing details of an outage over. Please include as much detail as possible.\nEmergency - only to be used if you are handing over an active incident to the AU team to continue work on.\n----\n\nCheers,\nMike\n" "handover-email" nil nil nil nil nil nil)
                       ("this-week" "To: support-team@squiz.com.au\nCc: sdm@squiz.com.au\nSubject: This Week in Support `(format-time-string \"%d/%m/%Y\")` - `(format-time-string \"%d/%m/%Y\" (time-add (current-time) (seconds-to-time 518400)))q`\n----\nGood morning everybody,\n \nFor the week commencing Monday `(format-time-string \"%d %B %Y\")`:\n \n*Leave*\n ${1:None}\n \n*Upgrades*\n | *Client* | *Who* | *Start* | *End* |\n |----------+-------+---------+-------|\n | $0         |       |         |       |\n \n*Scheduled Work*\n | *Detail* | *Date* |\n |----------+--------|\n |          |        |\n \n*Meetings*\n  ${2:None}\n\n*Triage:*\n  Morning: $3\n  Evening: $4\n\n*Week-ends:*\n  Saturday: $5\n  Sunday:   $6\n  SCRU:     $7\n\n*Other Notes:*\n  ${8:None}\n\n" "this-week-support" nil nil nil nil nil nil)))


;;; Do not edit! File generated at Tue Nov  3 11:10:52 2015
